<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IncrementsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $increments_table = array(
            array(
                "level_increments" => 1,
                "from_description" => "Can Read and Write",
                "to_description" => "Elementary Level Education",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 2,
                "from_description" => "Elementary Graduate",
                "to_description" => "Junior High School Level Education (K to 12)\nHigh School Level (Old curriculum)",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 3,
                "from_description" => "Completed Junior High School (K to 12)",
                "to_description" => "Senior High School Level Education (K to 12)",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 4,
                "from_description" => "Senior High School Graduate (K to 12)\nHigh School Graduate (Old curriculum)",
                "to_description" => "Less than 2 years of College",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 5,
                "from_description" => "Completed 2 years in College",
                "to_description" => "Less than a Bachelor's Degree but more than 2 years in College",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 6,
                "from_description" => "Bachelor's Degree",
                "to_description" => "Less than 6 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 7,
                "from_description" => "6 Units earned",
                "to_description" => "Less than 9 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 8,
                "from_description" => "9 Units earned",
                "to_description" => "Less than 12 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 9,
                "from_description" => "12 Units earned",
                "to_description" => "Less than 15 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 10,
                "from_description" => "15 Units earned ",
                "to_description" => "Less than 18 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 11,
                "from_description" => "18 Units earned",
                "to_description" => "Less than 21 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 12,
                "from_description" => "21 Units earned",
                "to_description" => "Less than 24 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 13,
                "from_description" => "24 Units earned",
                "to_description" => "Less than 27 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 14,
                "from_description" => "27 Units earned",
                "to_description" => "Less than 30 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 15,
                "from_description" => "30 Units earned",
                "to_description" => "Less than 33 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 16,
                "from_description" => "33 Units earned",
                "to_description" => "Less than 36 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 17,
                "from_description" => "36 Units earned",
                "to_description" => "Less than 39 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 18,
                "from_description" => "39 Units earned",
                "to_description" => "Less than 42 Units earned towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 19,
                "from_description" => "42 Units earned",
                "to_description" => "Less than Complete Academic Requirements completed towards the completion of a Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 20,
                "from_description" => "Complete Academic Requirements completed towards a Master's Degree",
                "to_description" => "Less than an awarded Master's Degree",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 21,
                "from_description" => "Master's Degree",
                "to_description" => "Less than 3 Units earned towards the completion of a Doctorate",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 22,
                "from_description" => "3 Units earned",
                "to_description" => "Less than 6 Units earned towards the completion of a Doctorate",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 23,
                "from_description" => "6 Units earned",
                "to_description" => "Less than 9 Units earned towards the completion of a Doctorate",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 24,
                "from_description" => "9 Units earned",
                "to_description" => "Less than 12 Units earned towards the completion of a Doctorate",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 25,
                "from_description" => "12 Units earned",
                "to_description" => "Less than 15 Units earned towards the completion of a Doctorate",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 26,
                "from_description" => "15 Units earned",
                "to_description" => "Less than 18 Units earned towards the completion of a Doctorate",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 27,
                "from_description" => "18 Units earned",
                "to_description" => "Less than 21 Units earned towards the completion of a Doctorate",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 28,
                "from_description" => "21 Units earned",
                "to_description" => "Less than 24 Units earned towards the completion of a Doctorate",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 29,
                "from_description" => "24 Units earned",
                "to_description" => "Less than Complete Academic Requirements completed towards the completion of a Doctorate",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 30,
                "from_description" => "Complete Academic Requirements completed towards a Doctorate",
                "to_description" => "Less than an awarded Doctorate",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 31,
                "from_description" => "Doctorate",
                "to_description" => "",
                "increments_type" => "education",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 1,
                "from_description" => "0 hours",
                "to_description" => "Less than 8 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 2,
                "from_description" => "8 hours",
                "to_description" => "Less than 16 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 3,
                "from_description" => "16 hours",
                "to_description" => "Less than 24 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 4,
                "from_description" => "24 hours",
                "to_description" => "Less than 32 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 5,
                "from_description" => "32 hours",
                "to_description" => "Less than 40 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 6,
                "from_description" => "40 hours",
                "to_description" => "Less than 48 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 7,
                "from_description" => "48 hours",
                "to_description" => "Less than 56 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 8,
                "from_description" => "56 hours",
                "to_description" => "Less than 64 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 9,
                "from_description" => "64 hours",
                "to_description" => "Less than 72 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 10,
                "from_description" => "72 hours",
                "to_description" => "Less than 80 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 11,
                "from_description" => "80 hours",
                "to_description" => "Less than 88 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 12,
                "from_description" => "88 hours",
                "to_description" => "Less than 96 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 13,
                "from_description" => "96 hours",
                "to_description" => "Less than 104 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 14,
                "from_description" => "104 hours",
                "to_description" => "Less than 112 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 15,
                "from_description" => "112 hours",
                "to_description" => "Less than 120 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 16,
                "from_description" => "120 hours",
                "to_description" => "Less than 128 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 17,
                "from_description" => "128 hours",
                "to_description" => "Less than 136 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 18,
                "from_description" => "136 hours",
                "to_description" => "Less than 144 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 19,
                "from_description" => "144 hours",
                "to_description" => "Less than 152 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 20,
                "from_description" => "152 hours",
                "to_description" => "Less than 160 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 21,
                "from_description" => "160 hours",
                "to_description" => "Less than 168 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 22,
                "from_description" => "168 hours",
                "to_description" => "Less than 176 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 23,
                "from_description" => "176 hours",
                "to_description" => "Less than 184 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 24,
                "from_description" => "184 hours",
                "to_description" => "Less than 192 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 25,
                "from_description" => "192 hours",
                "to_description" => "Less than 200 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 26,
                "from_description" => "200 hours",
                "to_description" => "Less than 208 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 27,
                "from_description" => "208 hours",
                "to_description" => "Less than 216 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 28,
                "from_description" => "216 hours",
                "to_description" => "Less than 224 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 29,
                "from_description" => "224 hours",
                "to_description" => "Less than 232 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 30,
                "from_description" => "232 hours",
                "to_description" => "Less than 240 hours",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 31,
                "from_description" => "240 hours",
                "to_description" => "or more",
                "increments_type" => "training",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 1,
                "from_description" => "None",
                "to_description" => "Less than 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 2,
                "from_description" => "6 months",
                "to_description" => "Less than 1 year",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 3,
                "from_description" => "1 year",
                "to_description" => "Less than 1 year 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 4,
                "from_description" => "1 year 6 months",
                "to_description" => "Less than 2 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 5,
                "from_description" => "2 years",
                "to_description" => "Less than 2 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 6,
                "from_description" => "2 years 6 months",
                "to_description" => "Less than 3 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 7,
                "from_description" => "3 years",
                "to_description" => "Less than 3 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 8,
                "from_description" => "3 years 6 months",
                "to_description" => "Less than 4 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 9,
                "from_description" => "4 years",
                "to_description" => "Less than 4 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 10,
                "from_description" => "4 years 6 months",
                "to_description" => "Less than 5 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 11,
                "from_description" => "5 years",
                "to_description" => "Less than 5 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 12,
                "from_description" => "5 years 6 months",
                "to_description" => "Less than 6 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 13,
                "from_description" => "6 years",
                "to_description" => "Less than 6 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 14,
                "from_description" => "6 years 6 months",
                "to_description" => "Less than 7 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 15,
                "from_description" => "7 years",
                "to_description" => "Less than 7 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 16,
                "from_description" => "7 years 6 months",
                "to_description" => "Less than 8 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 17,
                "from_description" => "8 years",
                "to_description" => "Less than 8 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 18,
                "from_description" => "8 years 6 months",
                "to_description" => "Less than 9 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 19,
                "from_description" => "9 years",
                "to_description" => "Less than 9 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 20,
                "from_description" => "9 years 6 months",
                "to_description" => "Less than 10 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 21,
                "from_description" => "10 years",
                "to_description" => "Less than 10 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 22,
                "from_description" => "10 years 6 months",
                "to_description" => "Less than 11 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 23,
                "from_description" => "11 years",
                "to_description" => "Less than 11 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 24,
                "from_description" => "11 years 6 months",
                "to_description" => "Less than 12 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 25,
                "from_description" => "12 years",
                "to_description" => "Less than 12 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 26,
                "from_description" => "12 years 6 months",
                "to_description" => "Less than 13 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 27,
                "from_description" => "13 years",
                "to_description" => "Less than 13 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 28,
                "from_description" => "13 years 6 months",
                "to_description" => "Less than 14 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 29,
                "from_description" => "14 years",
                "to_description" => "Less than 14 years 6 months",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 30,
                "from_description" => "14 years 6 months",
                "to_description" => "Less than 15 years",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
            array(
                "level_increments" => 31,
                "from_description" => "15 years",
                "to_description" => "or more",
                "increments_type" => "experience",
                "created_at" => "2024-10-22 03:22:07",
                "updated_at" => "2024-10-22 03:22:07",
            ),
        );

        foreach ($increments_table as $increment) {
                $increment['created_at'] = Carbon::now();
                $increment['updated_at'] = Carbon::now();
        }

        DB::table('increments_table')->insert($increments_table);
    }
}
