<?php

namespace Database\Seeders;

use App\Models\Jobtitle;
use Illuminate\Database\Seeder;

class JobtitleTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jobs =
            [
                [
                    'description' => "Accountant I",
                    'job_code' => 'A1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Accountant II",
                    'job_code' => 'A2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Accountant III",
                    'job_code' => 'A3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Accounting Analyst",
                    'job_code' => 'AA',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Accounting Clerk II",
                    'job_code' => 'AC2 ',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Aide I",
                    'job_code' => 'ADA1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Aide II",
                    'job_code' => 'ADA2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Aide III",
                    'job_code' => 'ADA3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Aide IV",
                    'job_code' => 'ADA4',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Aide V",
                    'job_code' => 'ADA5',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Aide VI",
                    'job_code' => 'ADA6',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Assistant I",
                    'job_code' => 'ADAS1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Assistant II",
                    'job_code' => 'ADAS2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Assistant III",
                    'job_code' => 'ADAS3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Assistant IV",
                    'job_code' => 'ADAS4',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Assistant V",
                    'job_code' => 'ADAS5',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Assistant VI",
                    'job_code' => 'ADAS6',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Officer I",
                    'job_code' => 'ADOF1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Officer II",
                    'job_code' => 'ADOF2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Officer III",
                    'job_code' => 'ADOF3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Officer IV",
                    'job_code' => 'ADOF4',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Administrative Officer V",
                    'job_code' => 'ADOF5',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Agriculturist I",
                    'job_code' => 'AG1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Agriculturist II",
                    'job_code' => 'AG2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Artist-Illustrator II",
                    'job_code' => 'AI2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Assistant Professor II",
                    'job_code' => 'AP2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Aquaculturist I",
                    'job_code' => 'AQ1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Aquacultural Technician II",
                    'job_code' => 'AQT2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Architect II",
                    'job_code' => 'ARC2 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Architect III",
                    'job_code' => 'ARC3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Assistant Special School Principal",
                    'job_code' => 'ASSP',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Assistant Secondary School Principal",
                    'job_code' => 'ASSP2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Assistant Schools Division Superintendent",
                    'job_code' => 'ASDS',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Assistant Teacher's Camp Superintendent",
                    'job_code' => 'ATCS',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Attorney I",
                    'job_code' => 'ATY1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Attorney II",
                    'job_code' => 'ATY2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Attorney III",
                    'job_code' => 'ATY3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Bookkeeper",
                    'job_code' => 'BKP ',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Cashier I",
                    'job_code' => 'CASH1 ',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Cashier II",
                    'job_code' => 'CASH2 ',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Creative Arts Specialist I",
                    'job_code' => 'CASL1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Creative Arts Specialist II",
                    'job_code' => 'CASL2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Crafts Education Demonstrator I",
                    'job_code' => 'CEDD1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Crafts Education Demonstrator II",
                    'job_code' => 'CEDD2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Chief Education Supervisor",
                    'job_code' => 'CES',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Communications Equipment Operator II",
                    'job_code' => 'CEO2 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Communications Equipment Operator III",
                    'job_code' => 'CEO3 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Computer File Librarian I",
                    'job_code' => 'CFL1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Computer File Librarian II",
                    'job_code' => 'CFL2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Clerk I",
                    'job_code' => 'CK1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Clerk II",
                    'job_code' => 'CK2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Clerk III",
                    'job_code' => 'CK3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "College Librarian I",
                    'job_code' => 'CL1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "College Librarian II",
                    'job_code' => 'CL2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Construction and Maintenance Man",
                    'job_code' => 'CMM',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Cook I",
                    'job_code' => 'COK1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Computer Programmer I",
                    'job_code' => 'COMPRO1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Computer Programmer II",
                    'job_code' => 'COMPRO2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Computer Programmer III",
                    'job_code' => 'COMPRO3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Coxswain",
                    'job_code' => 'COX ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Copy Reader",
                    'job_code' => 'CPYR',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Computer Maintenance Technologist I",
                    'job_code' => 'CTMT1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Computer Maintenance Technologist II",
                    'job_code' => 'CTMT2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Computer Maintenance Technologist III",
                    'job_code' => 'CTMT3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Dentist I",
                    'job_code' => 'DENT1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Dentist II",
                    'job_code' => 'DENT2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Dentist III",
                    'job_code' => 'DENT3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Draftsman I",
                    'job_code' => 'DFM1 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Draftsman II",
                    'job_code' => 'DFM2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Disbursing Officer I",
                    'job_code' => 'DO1 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Disbursing Officer II",
                    'job_code' => 'DO2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Dormitory Manager I",
                    'job_code' => 'DORMG1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Dormitory Manager II",
                    'job_code' => 'DORMG2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Driver I",
                    'job_code' => 'DRV1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Dental Aide",
                    'job_code' => 'DTA',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Education Research Assistant II",
                    'job_code' => 'EDRA2 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Engineer II",
                    'job_code' => 'ENG2 ',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Engineer III",
                    'job_code' => 'ENG3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Education Program Supervisor",
                    'job_code' => 'EPS',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Education Program Specialist I",
                    'job_code' => 'EPS1 ',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Education Program Specialist II",
                    'job_code' => 'EPS2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Education Supervisor I",
                    'job_code' => 'ESUP1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Executive Director II",
                    'job_code' => 'EXED2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Farm Worker I",
                    'job_code' => 'FAWK1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Fisherman",
                    'job_code' => 'FISM',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Guidance Coordinator I",
                    'job_code' => 'GCOOR1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Guidance Coordinator II",
                    'job_code' => 'GCOOR2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Guidance Coordinator III",
                    'job_code' => 'GCOOR3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Guidance Services Specialist I",
                    'job_code' => 'GSS1 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Guidance Services Specialist II",
                    'job_code' => 'GSS2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Guesthouse Caretaker",
                    'job_code' => 'GUESTC',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Guidance Counselor I",
                    'job_code' => 'GUIDC1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Guidance Counselor II",
                    'job_code' => 'GUIDC2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Guidance Counselor III",
                    'job_code' => 'GUIDC3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Handicraft Worker I",
                    'job_code' => 'HANDW1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Handicraft Worker II",
                    'job_code' => 'HANDW2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Heavy Equipment Operator I",
                    'job_code' => 'HEO1 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Health Education and Promotion Officer II ",
                    'job_code' => 'HEPO2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Health Education and Promotion Officer III",
                    'job_code' => 'HEPO3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Houseparent I",
                    'job_code' => 'HP1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Human Resource Management Officer I",
                    'job_code' => 'HRMO1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Human Resource Management Officer II",
                    'job_code' => 'HRMO2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Head Teacher I",
                    'job_code' => 'HTEACH1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Head Teacher II",
                    'job_code' => 'HTEACH2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Head Teacher III",
                    'job_code' => 'HTEACH3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Head Teacher IV",
                    'job_code' => 'HTEACH4',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Head Teacher V",
                    'job_code' => 'HTEACH5',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Head Teacher VI",
                    'job_code' => 'HTEACH6',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Internal Auditing Assistant",
                    'job_code' => 'IAAS',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Internal Auditor I",
                    'job_code' => 'IAUD1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Internal Auditor II",
                    'job_code' => 'IAUD2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Internal Auditor III",
                    'job_code' => 'IAUD3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Information Systems Analyst II",
                    'job_code' => 'INFOSA2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Information Systems Analyst III",
                    'job_code' => 'INFOSA3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Information Systems Researcher III",
                    'job_code' => 'INFOSR3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Instructor I",
                    'job_code' => 'INST1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Instructor II",
                    'job_code' => 'INST2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Instructor III",
                    'job_code' => 'INST3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Information Technology Officer I",
                    'job_code' => 'ITO1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Information Technology Officer II",
                    'job_code' => 'ITO2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Laboratory Technician I",
                    'job_code' => 'LABT1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Legal Assistant I",
                    'job_code' => 'LEA1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Legal Assistant II",
                    'job_code' => 'LEA2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Legal Aide",
                    'job_code' => 'LEAD',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Light Equipment Operator",
                    'job_code' => 'LEQO ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Librarian I",
                    'job_code' => 'LIB1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Librarian II",
                    'job_code' => 'LIB2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Laundry Woman",
                    'job_code' => 'LW',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Medical Officer II",
                    'job_code' => 'MDOF2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Medical Officer III",
                    'job_code' => 'MDOF3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Medical Officer IV",
                    'job_code' => 'MDOF4',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Marine Engineman I",
                    'job_code' => 'ME1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Mechanic I",
                    'job_code' => 'MECH1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Mechanic II",
                    'job_code' => 'MECH2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Master Fisherman I",
                    'job_code' => 'MFISH1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Mechanical Plant Operator I",
                    'job_code' => 'MPO1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Messenger",
                    'job_code' => 'MSGR',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Master Teacher I",
                    'job_code' => 'MTCHR1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Master Teacher II",
                    'job_code' => 'MTCHR2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Master Teacher III",
                    'job_code' => 'MTCHR3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Master Teacher IV",
                    'job_code' => 'MTCHR4',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Metal Worker I",
                    'job_code' => 'MTW1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Nursing Attendant I",
                    'job_code' => 'NATT1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Nutritionist Dietitian I",
                    'job_code' => 'ND1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Nutritionist-Dietitian II",
                    'job_code' => 'ND2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Nutritionist-Dietitian III",
                    'job_code' => 'ND3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Nurse Maid I",
                    'job_code' => 'NM1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Nurse I",
                    'job_code' => 'NURS1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Nurse II",
                    'job_code' => 'NURS2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Project Development Assistant",
                    'job_code' => 'PDA',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Project Development Officer I",
                    'job_code' => 'PDO1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Project Development Officer II",
                    'job_code' => 'PDO2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Project Development Officer III",
                    'job_code' => 'PDO3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Project Evaluation Officer IV",
                    'job_code' => 'PEO4',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Photoengraver II",
                    'job_code' => 'PHOEN2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Planning Officer I",
                    'job_code' => 'PLO1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Planning Officer II",
                    'job_code' => 'PLO2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Planning Officer III",
                    'job_code' => 'PLO3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Publication Production Supervisor",
                    'job_code' => 'PPROS',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Public Schools District Supervisor",
                    'job_code' => 'PSDS',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Printing Foreman",
                    'job_code' => 'PRINF',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Proofreader II",
                    'job_code' => 'PROOF2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Psychologist I",
                    'job_code' => 'PSY1 ',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Registar I",
                    'job_code' => 'R1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Registrar II",
                    'job_code' => 'R2 ',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Reproduction Machine Operator I",
                    'job_code' => 'RMO1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Records Officer II",
                    'job_code' => 'RO2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Senior Administrative Assistant I",
                    'job_code' => 'SADAS1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Senior Administrative Assistant II",
                    'job_code' => 'SADAS2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Senior Administrative Assistant III",
                    'job_code' => 'SADAS3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Senior Administrative Assistant V",
                    'job_code' => 'SADAS5',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Supervising Administrative Officer ",
                    'job_code' => 'SADOF',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Security Guard I",
                    'job_code' => 'SECG1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Security Guard II",
                    'job_code' => 'SECG2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Security Guard III",
                    'job_code' => 'SECG3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Secondary School Principal",
                    'job_code' => 'SECSP2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Farming Coordinator I",
                    'job_code' => 'SFC1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Farming Coordinator II",
                    'job_code' => 'SFC2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Farming Coordinator III",
                    'job_code' => 'SFC3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Farm Demonstrator",
                    'job_code' => 'SFD ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Librarian I ",
                    'job_code' => 'SL1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Librarian II",
                    'job_code' => 'SL2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Librarian III",
                    'job_code' => 'SL3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Social Welfare Officer I",
                    'job_code' => 'SOCWO1 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Principal I",
                    'job_code' => 'SP1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Principal II",
                    'job_code' => 'SP2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Principal III",
                    'job_code' => 'SP3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "School Principal IV",
                    'job_code' => 'SP4',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Special Education Teacher I",
                    'job_code' => 'SPET1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Special Education Teacher II",
                    'job_code' => 'SPET2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Special Education Teacher III",
                    'job_code' => 'SPET3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Special Education Teacher IV",
                    'job_code' => 'SPET4',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Special Education Teacher V",
                    'job_code' => 'SPET5',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Special Investigator II",
                    'job_code' => 'SPI2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Special Investigator III",
                    'job_code' => 'SPI3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Special School Principal I",
                    'job_code' => 'SPSP1 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Special School Principal II",
                    'job_code' => 'SPSP2 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Special Science Teacher I",
                    'job_code' => 'SPST1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Science Research Assistant",
                    'job_code' => 'SRAS',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Science Research Specialist II",
                    'job_code' => 'SRAS2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Senior Bookkeeper",
                    'job_code' => 'SRBK ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Senior Education Program Specialist",
                    'job_code' => 'SREPS',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Senior Science Research Specialist",
                    'job_code' => 'SRSRS',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Science Research Technician I",
                    'job_code' => 'SRT1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Science Research Technician II",
                    'job_code' => 'SRT2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Science Research Technician III",
                    'job_code' => 'SRT3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Science Research Technician IV",
                    'job_code' => 'SRT4',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Schools Division Superintendent",
                    'job_code' => 'SDS',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Statistician I",
                    'job_code' => 'STAT1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Statistician II",
                    'job_code' => 'STAT2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Statistician III",
                    'job_code' => 'STAT3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Statistician Aide",
                    'job_code' => 'STATA',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Supply Officer I",
                    'job_code' => 'SUO1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Supply Officer II",
                    'job_code' => 'SUO2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Supervising Education Program Specialist",
                    'job_code' => 'SVEPS ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Supervising Health Program Officer",
                    'job_code' => 'SVHPO',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Teaching Aids Specialist",
                    'job_code' => 'TAS',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Teacher Credentials Evaluator I",
                    'job_code' => 'TCE1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Teacher Credentials Evaluator II",
                    'job_code' => 'TCE2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Teacher I",
                    'job_code' => 'TCH1',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Teacher II",
                    'job_code' => 'TCH2',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Teacher III",
                    'job_code' => 'TCH3',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Teacher IV",
                    'job_code' => 'TCH4',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Teacher V",
                    'job_code' => 'TCH5',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Teacher VI",
                    'job_code' => 'TCH6',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Teacher VII",
                    'job_code' => 'TCH7',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Typesetter II",
                    'job_code' => 'TYPS2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Utility Foreman",
                    'job_code' => 'UTF',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Utility Worker I",
                    'job_code' => 'UTW1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Vocational Instruction Supervisor I",
                    'job_code' => 'VOCIS1 ',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Vocational Instruction Supervisor II",
                    'job_code' => 'VOCIS2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Vocational Instruction Supervisor III",
                    'job_code' => 'VOCIS3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Vocational Placement Coordinator I",
                    'job_code' => 'VOCPC1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Vocational School Administrator I",
                    'job_code' => 'VOCSA1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Vocational School Administrator II",
                    'job_code' => 'VOCSA2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Vocational School Superintendent I",
                    'job_code' => 'VOCSS',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Watchman I",
                    'job_code' => 'WCHM1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Watchman II",
                    'job_code' => 'WCHM2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Warehouseman I",
                    'job_code' => 'WH1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Warehouseman II",
                    'job_code' => 'WH2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Warehouseman III",
                    'job_code' => 'WH3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Attorney IV",
                    'job_code' => 'ATY4',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Chief Administrative Officer",
                    'job_code' => 'CADOF',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Director I",
                    'job_code' => 'DIR1',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Director II",
                    'job_code' => 'DIR2',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Director III",
                    'job_code' => 'DIR3',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Director IV",
                    'job_code' => 'DIR4',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Project Development Officer IV",
                    'job_code' => 'PDO4',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Project Development Officer V",
                    'job_code' => 'PDO5',
                    'is_available' => 0,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
                [
                    'description' => "Casual Clerk",
                    'job_code' => 'CC',
                    'is_available' => 1,
                    'created_at' => date('Y-m-d H:i:s'),
                ],
            ];

        Jobtitle::insert($jobs);
    }
}
